# Generated by Django 4.2.6 on 2023-11-09 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeupArtist', '0002_categoriaservicio_producto_stock_servicio_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
